### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by 12people** [pachisi456/clocktrol#13]
Would you be willing to add an open-source license to this project?

**Comment by pachisi456** [comment]
Hi @12people!
Thanks for opening this.
I am happy to include a license.
I'm curious. How did you find this and why is it interesting for you? What are you planning to use it for? :)

**Comment by 12people** [comment]
I came across this project when looking for a different one ([TimeCop](https://github.com/hamaluik/timecop), which is also a timer-related app). I was thinking of porting it to Linux in my free time sometime, and, having come across your project, was thinking perhaps it could be useful for Clockify integration down the line or perhaps just as a separate project. No specific plans, though. :)
